[pytest]
pythonpath = .

addopts = --alluredir=allure-results --clean-alluredir -v

testpaths = tests/saucedemo

markers =
    smoke: быстрые тесты для проверки базы
    regression: полная проверка функционала